"""
assemble_figures.py

Composites individual panel PNGs (generated by the MATLAB/R/Python pipeline)
into publication-ready compound figures following NHB layout standards:
  - double-column width: 180 mm
  - single-column width:  88 mm
  - min font size: 7 pt (inherited from source panels)
  - 300 DPI output, Arial bold panel labels (11 pt)

Figures produced
----------------
  Fig1_basic_behaviour.png/pdf   – panels a–e
  Fig2_factor_analysis.png/pdf   – panels a–c
  Fig3_OC_initial.png/pdf        – panels a–b
  Fig4_abPE.png/pdf              – panels a–d
  Fig5_sPE.png/pdf               – panels a–c, e–f
"""

import os
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib.image as mpimg

MM2IN = 1 / 25.4

FIG_DIR = '/Users/georgetertikas/Documents/Nadescha_code/figures'
OUT_DIR = os.path.join(FIG_DIR, 'compound')
os.makedirs(OUT_DIR, exist_ok=True)

plt.rcParams.update({'font.family': 'Arial', 'font.size': 8})


# ── helpers ──────────────────────────────────────────────────────────────────

def img(fname, crop_cols=None):
    """Load image; optionally crop to crop_cols=(start, end) column range."""
    data = mpimg.imread(os.path.join(FIG_DIR, fname))
    if crop_cols is not None:
        data = data[:, crop_cols[0]:crop_cols[1], :]
    return data

def show(ax, image):
    ax.imshow(image, interpolation='lanczos')
    ax.axis('off')

def plabel(ax, letter, x=-0.04, y=1.03):
    """NHB-style bold panel label, positioned just above top-left corner."""
    ax.text(x, y, letter,
            transform=ax.transAxes,
            fontsize=11, fontweight='bold',
            va='bottom', ha='right',
            fontfamily='Arial')

def save(name):
    for ext in ('png', 'pdf'):
        path = os.path.join(OUT_DIR, f'{name}.{ext}')
        plt.savefig(path, dpi=300, bbox_inches='tight', facecolor='white')
    plt.close()
    print(f'  saved: {name}.png / .pdf')


# ═══════════════════════════════════════════════════════════════════════════════
# FIGURE 1 – Basic Behaviour
#   a: overall performance boxplot (FB vs no-FB)
#   b: switch count histogram
#   c: FB performance by structural change number
#   d: no-FB performance by structural change number
#   e: LME effect-size bar (no-FB ~ FB)
# ═══════════════════════════════════════════════════════════════════════════════
print('\nFig 1: Basic Behaviour')

# Pre-load panels
im_a = img('Fig2a_performance_boxplot.png')
im_b = img('Fig2b_switch_histogram.png')
im_c = img('Fig2c_FB_by_switch.png')
im_d = img('Fig2d_noFB_by_switch.png')
im_e = img('Fig2e_LME_noFB_bar.png')

# Width ratios chosen to respect natural aspect ratios as closely as possible.
# Row 1: a (~square 0.98) | b (~square 1.10) – give a less width than b
# Row 2: c (landscape 1.33) | d (landscape 1.33) | e (portrait 0.93)
fig = plt.figure(figsize=(180*MM2IN, 140*MM2IN))
gs  = gridspec.GridSpec(2, 12, figure=fig, hspace=0.08, wspace=0.05)

# Row 1
ax_a = fig.add_subplot(gs[0, 0:4])
ax_b = fig.add_subplot(gs[0, 4:8])
ax_c = fig.add_subplot(gs[0, 8:12])   # histogram on the right

# Row 2
ax_d = fig.add_subplot(gs[1, 0:5])
ax_e = fig.add_subplot(gs[1, 5:10])
ax_f = fig.add_subplot(gs[1, 10:12])

show(ax_a, im_a); plabel(ax_a, 'a')
show(ax_b, im_b); plabel(ax_b, 'b')
show(ax_c, im_b); plabel(ax_c, 'b')   # placeholder; will be replaced below

# Redo rows: the actual panels are a–e, not a–f, so use correct layout
plt.close()

# Cleaner 2-row layout
fig = plt.figure(figsize=(180*MM2IN, 135*MM2IN))
gs  = gridspec.GridSpec(2, 10, figure=fig, hspace=0.10, wspace=0.06)

# Row 1: a (small) | b (histogram) | (gap)
ax_a = fig.add_subplot(gs[0, 0:3])
ax_b = fig.add_subplot(gs[0, 3:7])
# Row 1 right area left empty (matches original layout where a & b are smaller)

# Row 2: c (landscape) | d (landscape) | e (portrait)
ax_c = fig.add_subplot(gs[1, 0:4])
ax_d = fig.add_subplot(gs[1, 4:8])
ax_e = fig.add_subplot(gs[1, 8:10])

show(ax_a, im_a); plabel(ax_a, 'a')
show(ax_b, im_b); plabel(ax_b, 'b')
show(ax_c, im_c); plabel(ax_c, 'c')
show(ax_d, im_d); plabel(ax_d, 'd')
show(ax_e, im_e); plabel(ax_e, 'e')

# Hide the empty top-right area
for col in range(7, 10):
    fig.add_subplot(gs[0, col]).set_visible(False)

save('Fig1_basic_behaviour')


# ═══════════════════════════════════════════════════════════════════════════════
# FIGURE 2 – Factor Analysis
#   a: factor loading heatmap (portrait, tall)
#   b: scree plot
#   c: factor correlation matrix
# ═══════════════════════════════════════════════════════════════════════════════
print('\nFig 2: Factor Analysis')

# The MATLAB-generated Fig3a stores row-labels on the left (cols 0-522)
# and the actual heatmap starting at col 540; use only the heatmap portion.
im_a = img('Fig3a_factor_loadings_heatmap.png', crop_cols=(540, None))
im_b = img('Fig3b_scree_plot.png')
im_c = img('Fig3c_factor_correlations.png')

fig = plt.figure(figsize=(180*MM2IN, 150*MM2IN))
gs  = gridspec.GridSpec(2, 5, figure=fig, hspace=0.12, wspace=0.08)

ax_a = fig.add_subplot(gs[0:2, 0:3])  # tall left panel
ax_b = fig.add_subplot(gs[0,   3:5])  # top right
ax_c = fig.add_subplot(gs[1,   3:5])  # bottom right

show(ax_a, im_a); plabel(ax_a, 'a')
show(ax_b, im_b); plabel(ax_b, 'b')
show(ax_c, im_c); plabel(ax_c, 'c')

save('Fig2_factor_analysis')


# ═══════════════════════════════════════════════════════════════════════════════
# FIGURE 3 – OC trait and initial performance / comprehension
#   a: OC score vs initial performance (with marginal histograms)
#   b: OC score vs comprehension question repetitions (with marginals)
# ═══════════════════════════════════════════════════════════════════════════════
print('\nFig 3: OC vs initial performance & comprehension')

im_a = img('Fig4a_OC_vs_initial_perf.png')
im_b = img('Fig4b_OC_vs_MC_reps.png')

fig = plt.figure(figsize=(180*MM2IN, 90*MM2IN))
gs  = gridspec.GridSpec(1, 2, figure=fig, wspace=0.08)

ax_a = fig.add_subplot(gs[0, 0])
ax_b = fig.add_subplot(gs[0, 1])

show(ax_a, im_a); plabel(ax_a, 'a')
show(ax_b, im_b); plabel(ax_b, 'b')

save('Fig3_OC_initial_performance')


# ═══════════════════════════════════════════════════════════════════════════════
# FIGURE 4 – Absolute prediction error and OC
#   a: OC score vs # structural changes (with marginals)
#   b: FB performance around structural change (MB t-1, t, t+1)
#   c: OC score vs FB performance MB t+1 (with marginals)
#   d: GLMM coefficient plot (ab-PE × OC, MB t+1 model)
# ═══════════════════════════════════════════════════════════════════════════════
print('\nFig 4: abPE × OC')

im_a = img('Fig5a_OC_vs_switches.png')
im_b = img('Fig5b_FB_prepost_MB.png')
im_c = img('Fig5c_OC_vs_FB_MBt1.png')
im_d = img('Fig5de_GLMM_abPE_bar.png')

fig = plt.figure(figsize=(180*MM2IN, 150*MM2IN))
gs  = gridspec.GridSpec(2, 2, figure=fig, hspace=0.10, wspace=0.08)

ax_a = fig.add_subplot(gs[0, 0])
ax_b = fig.add_subplot(gs[0, 1])
ax_c = fig.add_subplot(gs[1, 0])
ax_d = fig.add_subplot(gs[1, 1])

show(ax_a, im_a); plabel(ax_a, 'a')
show(ax_b, im_b); plabel(ax_b, 'b')
show(ax_c, im_c); plabel(ax_c, 'c')
show(ax_d, im_d); plabel(ax_d, 'd')

save('Fig4_abPE_OC')


# ═══════════════════════════════════════════════════════════════════════════════
# FIGURE 5 – Signed prediction error and OC
#   a: no-FB performance × OC interaction (LMM, MBs since switch)
#   b: no-FB performance around structural change (MB t-1, t, t+1)
#   c: OC score vs no-FB performance MB t+1 (with marginals)
#   d: [schematic – not generated computationally; placeholder blank]
#   e: GLMM coefficient plot (s-PE × OC)
#   f: GLMM coefficient plot (Δs-PE × OC)
# ═══════════════════════════════════════════════════════════════════════════════
print('\nFig 5: sPE × OC')

im_a = img('Fig6a_interaction_noFB_MBsinceSW.png')
im_b = img('Fig6b_noFB_prepost_MB.png')
im_c = img('Fig6c_OC_vs_noFB_MBt1.png')
im_e = img('Fig6e_GLMM_sPE_bar.png')
im_f = img('Fig6f_GLMM_sPE_change_bar.png')

# Layout: 2 rows × 12 cols
#   Row 1: a (landscape, 0:7) | b (portrait, 7:12)
#   Row 2: c (square, 0:3) | d placeholder (3:6) | e (6:9) | f (9:12)
fig = plt.figure(figsize=(180*MM2IN, 150*MM2IN))
gs  = gridspec.GridSpec(2, 12, figure=fig, hspace=0.10, wspace=0.06)

ax_a = fig.add_subplot(gs[0, 0:7])    # landscape interaction plot
ax_b = fig.add_subplot(gs[0, 7:12])   # bar chart

ax_c = fig.add_subplot(gs[1, 0:3])    # scatter + marginals
ax_d = fig.add_subplot(gs[1, 3:6])    # schematic placeholder
ax_e = fig.add_subplot(gs[1, 6:9])    # GLMM sPE
ax_f = fig.add_subplot(gs[1, 9:12])   # GLMM sPE_change

show(ax_a, im_a); plabel(ax_a, 'a')
show(ax_b, im_b); plabel(ax_b, 'b')
show(ax_c, im_c); plabel(ax_c, 'c')
show(ax_e, im_e); plabel(ax_e, 'e')
show(ax_f, im_f); plabel(ax_f, 'f')

# Panel d: schematic placeholder
ax_d.set_facecolor('#f5f5f5')
ax_d.text(0.5, 0.5, 'schematic\n(panel d)', ha='center', va='center',
          fontsize=8, color='#999999', style='italic',
          transform=ax_d.transAxes)
ax_d.set_xticks([]); ax_d.set_yticks([])
for sp in ax_d.spines.values():
    sp.set_edgecolor('#cccccc'); sp.set_linewidth(0.5)
plabel(ax_d, 'd')

save('Fig5_sPE_OC')


print('\nAll compound figures saved to:', OUT_DIR)
